version: '3'

services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: antlypls/zookeeper

  kafka:
    container_name: kafka
    hostname: kafka
    image: antlypls/kafka
    depends_on:
    - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1,error:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

